### ISSUE TITLE
Not rendering extra environment variables correctly (relay template)

### ISSUE THREAD

**Issue by 200sc** [strongdm/charts#11]
Given a values file like:
```
global:
  ...
  extraEnvironmentVars:
    - name: ABC_EFG
      value: "hello"
```

The template renders:
```
        env:        
        - name: "%!S(INT=0)"
          value: "map[name:ABC_EFG value:hello]"
```

Making the following change appears to correct:
```
remove:
        {{- include "sdm.extraEnvironmentVars" .Values.global | indent 8 }}
add:
        {{- range .Values.global.extraEnvironmentVars }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
```

Opened on @wcraigjones behalf
