### ISSUE TITLE
[BUG] helm install fails, duplicate labels for app.kubernetes.io/instance

### ISSUE THREAD

**Issue by georambo** [strongdm/charts#43]
**Describe the bug**
When try to do a helm install, it fails with the following error

```
strongdm	2.0.0   	False    	False	Helm install failed for release strongdm/strongdm with chart sdm-proxy@2.0.0: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors:
        	        	         	     	  line 14: mapping key "app.kubernetes.io/instance" already defined at line 10
```
The problem is that when you render the helm manifest, you get duplicate keys of `app.kubernetes.io/instance`

```
---
# Source: sdm-relay/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: strongdm-config
  namespace: strongdm
  annotations:
    
  labels:
    app.kubernetes.io/name: sdm-relay
    app.kubernetes.io/instance: strongdm
    app.kubernetes.io/component: relay
    helm.sh/chart: sdm-relay-2.0.0
    helm.sh/release: strongdm
    app.kubernetes.io/instance: strongdm
    app.kubernetes.io/managed-by: Helm
    date: 2025-04-30
```

**To Reproduce**
1.do a helm install with chart version 2.0.0

**Expected behavior**
helm chart should install
