### ISSUE TITLE
[BUG]Cannot install chart with auth.adminToken only

### ISSUE THREAD

**Issue by georambo** [strongdm/charts#52]
**Describe the bug**
When installing the sdm-relay chart with the below helm values

```
global:
  addDateLabel: true

strongdm:
  image:
    pullPolicy: IfNotPresent
    repository: 769770408374.dkr.ecr.us-east-1.amazonaws.com/mirrors/public.ecr.aws/strongdm/relay
    tag: 47.47.0
    digest: ""
  config:
    additionalEnvVars:
      SDM_HTTPS_PROXY: http://webproxy:3128
  auth:
    adminToken:  <redacted>
```

we get this error
```
strongdm-gw-67576f95c4-zxlfl   0/1     CreateContainerConfigError   0          8m11s
```
describing the pod we can see
```
  Warning  Failed     6s (x9 over 87s)  kubelet            Error: secret "strongdm-gw-relay-token" not found
```

I believe the error is because this line https://github.com/strongdm/charts/blob/main/deployments/sdm-relay/templates/deployment.yaml#L51
```
- name: SDM_RELAY_TOKEN
              valueFrom:
                secretKeyRef:
                  key: SDM_RELAY_TOKEN
                  name: {{ .Values.strongdm.autoCreateNode.enabled | ternary (printf "%s-relay-token" .Release.Name) (default (printf "%s-secrets" .Release.Name) .Values.strongdm.auth.secretName) }}
```

This is assume that a secret exists with the relayToken.  We should not have to provide a relay token secret though right? we already pass in the adminToken as a value.

**To Reproduce**
1. Use the helm values above
2. Install the chart

**Expected behavior**
The sdm relay pod should start and register with the control plane.
